### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by JuergenReppSIT** [joholl/tpmstream-web#1]
A useful tool. Now there is no need for me to start my ubuntu 22.04 vm because tpmstream did not work on ubuntu 20.04.
Thank you!
Perhaps you could add an example how to use it to the README. E.g.:
```
tpm2_getrandom -Tpcap:device:/dev/tpmrm0 -o /tmp/rand 10
xxd -p tpm2_log.pcap| tr -d "\n"
```

**Comment by joholl** [comment]
Yeah, I'm not testing for older python versions, currently. I added an example, thanks for your input.

Glad that you find it useful!
